const { test, expect } = require('@playwright/test');

/**
 * Tests on the character page elements
 */
const baseUrl = 'http://0.0.0.0:3000/'

test('Character  Render Test', async ({ page }) => {
  await page.goto(`${baseUrl}/character/9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8`);

  const characterName = await page.textContent('.char-name');
  const species = await page.textContent('.char-species');
  const gender = await page.textContent('.char-gender');
  const house = await page.textContent('.char-house');
  const image = await page.getAttribute('img', 'src');

  expect(characterName).toContain('Harry Potter');
  expect(species).toContain('human');
  expect(gender).toContain('male');
  expect(house).toContain('Gryffindor');
  expect(image).toContain('https://ik.imagekit.io/hpapi/harry.jpg');
});

test('Tests generated by codeGen ', async ({ page }) => {
  await page.goto(`${baseUrl}`);
  await page.getByRole('heading', { name: 'Harry Potter Characters'});
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByPlaceholder('Search Name, House...').click();
  await page.locator('div').filter({ hasText: 'Name: Hermione GrangerD.O.B: 19-09-1979Read more' }).nth(1).click();
  await page.getByPlaceholder('Search Name, House...').click();
  await page.getByPlaceholder('Search Name, House...').fill('Harry');
  await page.locator('section').filter({ hasText: /^SearchSearchName: Harry PotterD\.O\.B: 31-07-1980Read more$/ }).locator('img');
  await page.locator('section').filter({ hasText: /^SearchSearchName: Harry PotterD\.O\.B: 31-07-1980Read more$/ }).getByRole('heading');
  await page.locator('section').filter({ hasText: /^SearchSearchName: Harry PotterD\.O\.B: 31-07-1980Read more$/ }).getByRole('paragraph');
  await page.getByText('Name: Harry PotterD.O.B: 31-07-1980Read more').first();
  await page.locator('section').filter({ hasText: /^SearchSearchName: Harry PotterD\.O\.B: 31-07-1980Read more$/ }).getByRole('button').nth(1);
  await page.locator('div').filter({ hasText: 'Name: Harry PotterD.O.B: 31-07-1980Read more' }).nth(1);
  await page.getByPlaceholder('Search Name, House...').click();
  await page.locator('.mx-2 > .my-2').first().click();
  await page.getByRole('img', { name: 'Harry Potter' });
  await page.locator('div').nth(1);
  await page.getByText('Alternate Names: The Boy Who Lived, The Chosen One');
  await page.getByText('D.O.B: 31-07-1980');
  await page.getByText('Y.O.B: 1980');
  await page.getByText('Wizard:true');
  await page.getByText('Species: human');
  await page.getByText('Gender: male');
  await page.getByText('House: Gryffindor');
  await page.getByText('Ancestry: half-blood');
  await page.getByText('Eye Colour: green');
  await page.getByText('Hair Colour: black');
});
